# Generated by Django 3.2.21 on 2024-06-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240625_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='previous_abs_difference_eye',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_abs_difference_eyebrows',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_abs_difference_mouth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_left_eye_area',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_left_eyebrow_distance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_left_mouth_distance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_right_eye_area',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_right_eyebrow_distance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='previous_right_mouth_distance',
        ),
    ]
