# Generated by Django 3.2.21 on 2024-06-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240627_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eye_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eyebrow_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mouth_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
