# Generated by Django 3.2.21 on 2024-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240628_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
