# Generated by Django 3.2.21 on 2024-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_date_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_selected',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
