# Generated by Django 3.2.21 on 2024-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240701_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_selected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
